import React, { useCallback, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  RefreshControl,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';

import { palette, spacing, borderRadius, shadows, typography } from '../../theme';
import { itinerariesService } from '../../services/itineraries.service';
import { Itinerary } from '../../types/itinerary';

export default function MyItinerariesScreen() {
  const { t } = useTranslation();
  const navigation = useNavigation<any>();
  const [items, setItems] = useState<Itinerary[]>([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  const fetchAll = useCallback(async () => {
    try {
      setLoading(items.length === 0);
      const res = await itinerariesService.listMine(1, 50);
      setItems(res.data);
    } catch (err: any) {
      const msg = err?.response?.data?.message || err?.message || t('error');
      Alert.alert(t('error'), msg);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [items.length, t]);

  useFocusEffect(
    useCallback(() => {
      fetchAll();
    }, [fetchAll])
  );

  const handleDelete = (id: string) => {
    Alert.alert(t('confirm'), t('itineraryDeleteConfirm'), [
      { text: t('cancel'), style: 'cancel' },
      {
        text: t('delete'),
        style: 'destructive',
        onPress: async () => {
          try {
            await itinerariesService.remove(id);
            setItems((prev) => prev.filter((i) => i._id !== id));
          } catch (err: any) {
            Alert.alert(t('error'), err?.response?.data?.message || t('error'));
          }
        },
      },
    ]);
  };

  const renderItem = ({ item }: { item: Itinerary }) => {
    const stops = item.days?.reduce((s, d) => s + (d.stops?.length || 0), 0) || 0;
    return (
      <TouchableOpacity
        style={styles.card}
        activeOpacity={0.85}
        onPress={() =>
          navigation.navigate('ItineraryResult', { itineraryId: item._id })
        }
      >
        <View style={styles.cardHeader}>
          <View style={{ flex: 1 }}>
            <Text style={styles.cardTitle} numberOfLines={1}>
              {item.title}
            </Text>
            <View style={styles.row}>
              <Ionicons name="calendar-outline" size={14} color={palette.gray500} />
              <Text style={styles.muted}>
                {t('daysCount', { count: item.durationDays })}
              </Text>
              <Text style={styles.dot}>·</Text>
              <Ionicons name="pin-outline" size={14} color={palette.gray500} />
              <Text style={styles.muted}>
                {t('stopsCount', { count: stops })}
              </Text>
            </View>
          </View>
          <View style={[styles.badge, statusStyle(item.status)]}>
            <Text style={styles.badgeText}>{t(`itineraryStatus.${item.status}`)}</Text>
          </View>
        </View>

        <View style={styles.cardFooter}>
          <View style={styles.row}>
            <Ionicons name="wallet-outline" size={14} color={palette.olive} />
            <Text style={styles.budget}>
              {item.totalCost.toFixed(0)} {item.currency}
            </Text>
            {item.generated && (
              <>
                <Text style={styles.dot}>·</Text>
                <Ionicons name="sparkles-outline" size={14} color={palette.gold} />
                <Text style={[styles.muted, { color: palette.gold }]}>
                  {t('itineraryAutoGenerated')}
                </Text>
              </>
            )}
          </View>
          <TouchableOpacity onPress={() => handleDelete(item._id)} hitSlop={8}>
            <Ionicons name="trash-outline" size={18} color={palette.error} />
          </TouchableOpacity>
        </View>
      </TouchableOpacity>
    );
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>{t('myItineraries')}</Text>
        <TouchableOpacity
          style={styles.createBtn}
          onPress={() => navigation.navigate('ItineraryPlanner')}
        >
          <Ionicons name="add" size={20} color={palette.white} />
          <Text style={styles.createBtnText}>{t('create')}</Text>
        </TouchableOpacity>
      </View>

      {loading && items.length === 0 ? (
        <ActivityIndicator style={{ marginTop: spacing.xl }} color={palette.mediterraneanBlue} />
      ) : (
        <FlatList
          contentContainerStyle={
            items.length === 0 ? styles.emptyWrap : styles.listContent
          }
          data={items}
          keyExtractor={(i) => i._id}
          renderItem={renderItem}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={() => {
                setRefreshing(true);
                fetchAll();
              }}
              tintColor={palette.mediterraneanBlue}
            />
          }
          ListEmptyComponent={
            <View style={styles.empty}>
              <Ionicons name="map-outline" size={64} color={palette.gray300} />
              <Text style={styles.emptyTitle}>{t('noItinerariesYet')}</Text>
              <Text style={styles.emptySubtitle}>{t('noItinerariesYetSubtitle')}</Text>
              <TouchableOpacity
                style={[styles.createBtn, { marginTop: spacing.lg }]}
                onPress={() => navigation.navigate('ItineraryPlanner')}
              >
                <Ionicons name="sparkles-outline" size={18} color={palette.white} />
                <Text style={styles.createBtnText}>{t('generateMyTrip')}</Text>
              </TouchableOpacity>
            </View>
          }
        />
      )}
    </View>
  );
}

const statusStyle = (status: Itinerary['status']) => {
  switch (status) {
    case 'active':
      return { backgroundColor: palette.successLight };
    case 'completed':
      return { backgroundColor: palette.gray200 };
    default:
      return { backgroundColor: palette.warningLight };
  }
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.gray50 },
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing['2xl'],
    paddingBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: { ...typography.h2, color: palette.gray900 },
  createBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: palette.mediterraneanBlue,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
  },
  createBtnText: { color: palette.white, fontWeight: '600', fontSize: 14 },
  listContent: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xl },
  card: {
    backgroundColor: palette.white,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  cardTitle: { ...typography.h4, color: palette.gray900, marginBottom: 4 },
  cardFooter: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  muted: { color: palette.gray500, fontSize: 13 },
  dot: { color: palette.gray300, marginHorizontal: 2 },
  budget: { color: palette.olive, fontSize: 14, fontWeight: '700' },
  badge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.full,
  },
  badgeText: { fontSize: 11, fontWeight: '600', color: palette.gray800 },
  emptyWrap: { flexGrow: 1, justifyContent: 'center', alignItems: 'center' },
  empty: { alignItems: 'center', paddingHorizontal: spacing.xl },
  emptyTitle: { ...typography.h3, color: palette.gray700, marginTop: spacing.md },
  emptySubtitle: {
    ...typography.body,
    color: palette.gray500,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
});
